### ISSUE TITLE
Postal code polygons - any versions without maritime extensions?

### ISSUE THREAD

**Issue by arvdv** [rOpenGov/geodk#1]
Hi there,

I've been using your version of GeoDK to avoid having to interact with dataforsygningen.dk directly and it's really worked like a charm - thanks! I've got a quick question - the polygons for postal codes seem to be extending coastal zones into the sea (to follow the Danish exclusive economic zone, I assume). Is there a chance that a version that stops at the coastline is available somewhere?

<img width="697" alt="image" src="https://github.com/user-attachments/assets/3772f24b-ab4e-44db-b033-ae52bb6ce0c9">

**Comment by aleksanderbl29** [comment]
Great to hear you've found some use of it.

That looks really weird! I have managed to reproduce the behaviour with `geodk::plot_denmark("postnumre")` and will look into it

**Comment by aleksanderbl29** [comment]
I have found the issue. It is completely expected behaviour. The postal code section of the api by default returns sea-area as well (pr. [the documentation](https://dawadocs.dataforsyningen.dk/dok/api/postnummer)). I will add the appropriate parameter in the `{dawaR}` package (which handles the API-requests) to change the default behaviour in our case.

I will update here when the patch is released

**Comment by aleksanderbl29** [comment]
Quick update. 
I have now committed the changes at [00abae0](https://github.com/aleksanderbl29/dawaR/pull/102/commits/00abae04bd025be9a6a51cb3ac9515b3a2da5fb5) and the new version should be published to r-universe as soon as the automatic checks pass.

**Comment by arvdv** [comment]
Awesome Aleksander, thanks for this! (also apologies for not actually providing you with a reproducible example to begin with)

**Comment by aleksanderbl29** [comment]
Great - No worries!!

I'll throw a comment here when it is released. It doesn't really pass CI. It will be ready soon™

**Comment by aleksanderbl29** [comment]
The `{dawaR}` package has now been release on r-universe. Please update with 
`install.packages("dawaR", repos = c("https://aleksanderbl29.r-universe.dev", "https://cloud.r-project.org"))`
